aved_calendrier:
    path:    /calendrier.{_format}
    defaults: { _controller: AvedBlogBundle:Default:calendrier, _format:html }
    requirements:
        _format: html|json|xml|ics
        _method:  GET